vich_uploader:
    db_driver: orm

    mappings:
        user_avatar_images:
            uri_prefix:         '%app.user.avatar_images%'
            upload_destination: '%kernel.project_dir%/public%app.user.avatar_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        fighter_avatar_images:
            uri_prefix:         '%app.fighter.avatar_images%'
            upload_destination: '%kernel.project_dir%/public%app.fighter.avatar_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
