name: Playwright Tests and Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
            cd front/    
            npm ci
      - name: Install Playwright Browsers
        run: |
            cd front/
            npx playwright install chromium
      - name: Run Playwright tests
        run: |
            cd front/
            npm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  Deploy-Production:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: |
            cd front/
            npm install --global vercel@latest
      - name: Install dependencies
        run: |
            cd front/
            npm ci
      - name: Pull Vercel Environment Information
        run: |
            cd front/
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
            cd front/
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
            cd front/
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
